name: Go

on: push

jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.14", "1.13"]
    name: Test, Lint, Format
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Setup go lint
        run: go get -u golang.org/x/lint/golint
      - uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - name: Lint
        run: golint -set_exit_status ./...
      - name: Format
        run: test -z $(gofmt -l -s .)
      - name: Vet
        run: go vet ./...
